### PR TITLE
Long run test app

### PR DESCRIPTION
**Pull request by AndrewAR2**
Long run test app

### CODE REVIEW

**Comment by avive** [comment]
Is this ready for merging into develop or not yet?
Maybe you can add few bullets of new features / changed things in this release?

**Comment by avive** [comment]
I'm getting an error trying to build on macOS. I see that in the CI this error is a warning only.

CMake Error at src/CMakeLists.txt:140 (add_subdirectory):
  The source directory

    /Users/avive/dev/gpu-post/src/vulkan/zlib

  does not contain a CMakeLists.txt file.

**Comment by AndrewAR2** [comment]
> Is this ready for merging into develop or not yet?

Yes, it is ready for merging.

**Comment by AndrewAR2** [comment]
> I'm getting an error trying to build on macOS. I see that in the CI this error is a warning only.

zlib is submodule, so you need to fetch it:
git submodule init
git submodule update

**Pull request merged**
