### PR TITLE
Added unit tests and integration tests

### PR DESCRIPTION
**Pull request by AndrewAR2**
Added unit tests and integration tests

### CODE REVIEW

**Comment by moshababo** [comment]
Thanks for the PR, will be reviewed soon.
In the meanwhile, can you please add the new tests to the CI (although the CI VM supports only the CPU provider)?

**Comment by avive** [comment]
It would be nice if the usage printf in the test app will document all of the new flags with 1 sentence...
test.cpp line # 303

**Comment by avive** [comment]
Running the unit tests via the test app uses excessive ram and crashes my mbp. Started to run it with 10GB free. Process gets to ~100GB allocated memory while testing the AMD gpu vulkan provider at around 60 bits. Might be a leak?

**Comment by avive** [comment]
Building and testing on Windows 10 pro both work okay with the latest Vulkan 1.2 sdk installed.

**Comment by avive** [comment]
I'm having some issues on OS X. Installed Vulkan 1.2 sdk. Running with -b fails.
```
aembp:test avive$ ./gpu-setup-test -l
Available POST compute providers:
  0: [VULKAN] AMD Radeon Pro 560X
  1: [VULKAN] Intel(R) UHD Graphics 630
  2: [CPU] CPU
aembp:test avive$ ./gpu-setup-test -b
Benchmark: Label size: 8, count 1179648, buffer 1.1M
AMD Radeon Pro 560X: 0 hashes, 0 h/s
Intel(R) UHD Graphics 630: 0 hashes, 0 h/s
```

-b works fine on Windows 10 pro.


-t output:
```
aembp:test avive$ ./gpu-setup-test -t
Test: Label size: 8, count 1179648, buffer 1.1M
CPU: 1179648 hashes, 9556 h/s
AMD Radeon Pro 560X: 0 hashes, 0 h/s
WRONG result for label size 8 from provider 0 [AMD Radeon Pro 560X]
Intel(R) UHD Graphics 630: 0 hashes, 0 h/s
WRONG result for label size 8 from provider 1 [Intel(R) UHD Graphics 630]
```

Here's VulkanInfo from this mbp:
```
Vulkan Development Status:
- VULKAN_SDK environment variable not set
- Vulkan Loader version: 1.2.154
- Custom Layers Paths: None
- Available Layers:
    - VK_LAYER_LUNARG_override
    - VK_LAYER_LUNARG_api_dump
    - VK_LAYER_KHRONOS_validation
- Physical Devices:
    - AMD Radeon Pro 560X (Discrete GPU) with Vulkan 1.1.154
    - Intel(R) UHD Graphics 630 (Integrated GPU) with Vulkan 1.1.154
```

Not sure what `with Vulkan 1.1.154` means because as far as I understand Vulkan is implemented as a layer over metal on os x....

**Comment by avive** [comment]
Having problems building on another OS X system. We should clarify the dev toolchain required versions.
Installed Vulkan SDK 1.2. 

```
AEP2:build auser$ make
[ 10%] Generating Vulkan Kernel Byte Array
Scanning dependencies of target gpu-setup
[ 20%] Building C object src/CMakeFiles/gpu-setup.dir/api.c.o
[ 30%] Building CXX object src/CMakeFiles/gpu-setup.dir/api_internal.cpp.o
[ 40%] Building CXX object src/CMakeFiles/gpu-setup.dir/scrypt-jane/scrypt-jane.cpp.o
[ 50%] Building C object src/CMakeFiles/gpu-setup.dir/vulkan/driver-vulkan.c.o
[ 60%] Building C object src/CMakeFiles/gpu-setup.dir/vulkan/vulkan-helpers.c.o
[ 70%] Building CXX object src/CMakeFiles/gpu-setup.dir/vulkan/glsl_compiler.cpp.o
[ 80%] Linking CXX shared library libgpu-setup.dylib
ld: warning: directory not found for option '-L/lib'
ld: library not found for -lshaderc_combined
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/libgpu-setup.dylib] Error 1
make[1]: *** [src/CMakeFiles/gpu-setup.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by AndrewAR2** [comment]
We tested on macOS again with Vulkan SDK 1.2.154.0 and all the time successfully.

**Comment by avive** [comment]
> We tested on macOS again with Vulkan SDK 1.2.154.0 and all the time successfully.

Can you please share hardware and gpu models plus os X version?

This is what I get on my system. I've got a fully updated 10.15.7 with the GPUs mentioned above.
```
aembp:~ avive$ /Applications/vulkaninfo.app/Contents/MacOS/vulkaninfo ; exit;
ERROR: [Loader Message] Code 0 : dlopen(/Users/avive/dev//vulkansdk-macos-1.1.130.0/macOS/etc/vulkan/icd.d/../../../lib/libMoltenVK.dylib, 5): no suitable image found.  Did find:
	/Users/avive/dev//vulkansdk-macos-1.1.130.0/macOS/etc/vulkan/icd.d/../../../lib/libMoltenVK.dylib: code signature in (/Users/avive/dev//vulkansdk-macos-1.1.130.0/macOS/etc/vulkan/icd.d/../../../lib/libMoltenVK.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at /Users/lunarg/Dev/macos-sdk-build/Vulkan-Tools/vulkaninfo/vulkaninfo.h:666:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.
```

**Comment by avive** [comment]
I had a bad env vars. This is useful for os X installation: https://github.com/spacemeshos/gpu-post/blob/unit-and-integration-tests2/.github/tools/macos-install-vulkan.sh

**Comment by avive** [comment]
I'm able to build the sdk from this branch on OS X fine but the lib doesn't see my AMD and Intel cards :-(

**Review by moshababo — APPROVED** [review]

**Pull request merged**
